test:
  name: my-asset-benchmark
  description: Benchmarking sample
  workers:
    type: local
    number: 2
  rounds:
    - label: readAsset
      description: Read asset benchmark test
      chaincodeId: mycc
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 2
      callback: benchmarks/callbacks/readAsset.js
      arguments:
        assets: 10
    - label: getAllAssets
      description: Get all assets benchmark test
      chaincodeId: mycc
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 2
      callback: benchmarks/callbacks/getAllAssets.js
    - label: getAssetHistory
      description: Get asset history benchmark test
      chaincodeId: mycc
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 2
      callback: benchmarks/callbacks/getAssetHistory.js
      arguments:
        assets: 10
    - label: createAsset
      description: Create asset benchmark test
      chaincodeId: mycc
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 2
      callback: benchmarks/callbacks/createAsset.js
    - label: updateAsset
      description: Update asset benchmark test
      chaincodeId: mycc
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 2
      callback: benchmarks/callbacks/updateAsset.js
      arguments:
        assets: 10
    - label: transferAsset
      description: Transfer asset benchmark test
      chaincodeId: mycc
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 2
      callback: benchmarks/callbacks/transferAsset.js
      arguments:
        assets: 10
    - label: deleteAsset
      description: Delete asset benchmark test
      chaincodeId: mycc
      txNumber: 100
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 2
      callback: benchmarks/callbacks/deleteAsset.js
      arguments:
        assets: 50
monitor:
  type:
  - none
observer:
  type: local
  interval: 5